version: '3'
services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    env_file:
      - .env.docker
    restart: unless-stopped

  # server:
  #   build:
  #     context: .
  #     dockerfile: ./server/src/Dockerfile
  #   ports:
  #     - 3000:3009
  #   env_file:
  #     - .env.docker
  #   depends_on:
  #     - db